### ISSUE TITLE
[FEATURE REQ] Add validation layer from client -> server for all routes

### ISSUE THREAD

**Issue by Propo41** [Cefalo/bookify#40]

**Comment by HazemAbdo** [comment]
@Propo41 I'd like to work on this feature, but I have a question. Is it acceptable to use a schema validator like Zod or Yup, or should we implement our own methods and helpers for validating basic input types? We don't have protected routes set up yet. Should we create a separate issue for that? I can also work on implementing it.

**Comment by Propo41** [comment]
Hi @HazemAbdo, you are most welcome to go ahead. Please follow the documentation here: https://docs.nestjs.com/techniques/validation

the package `class-validator` should be used to add the validation logic. 
It works by assigning decorators to the class fields. 

Check how the `createEvent()` endpoint is written. It takes a Dto class as an argument. You would have to do the same thing in all the relevant endpoints. The documentation link above explains it better.

**Comment by HazemAbdo** [comment]
@Propo41 I got it I thought it was frontend inputs validation but now I understand you well. Can you please assign it to me?
