### ISSUE TITLE
"Change Room" Button Not Working

### ISSUE THREAD

**Issue by jenyyy4** [Cefalo/bookify#43]
# Bug Report: "Change Room" Button Not Working

## Description
The "Change Room" button is unresponsive when clicked. It does not trigger the expected functionality (redirect to the room selection page or update the current room). This issue occurs  and affects the overall user experience. 

<img width="1440" alt="Button Issue Screenshot" src="https://github.com/user-attachments/assets/f3e212ab-0882-427f-afc0-7aed6284c1dc">

## Steps to Reproduce

1. Click on the “BOOK” button.
2. Locate the "Change Room" button.
3. Click on the "Change Room" button.
4. Observe that no action occurs.

## Expected Behavior
When the "Change Room" button is clicked, it should:
- Redirect to the room selection page **or**
- Trigger a modal/popup to select a new room **or**
- Update the room as per the selected choice.

## Actual Behavior
No action occurs after clicking the "Change Room" button. The page remains unchanged, and there is no indication of the button being functional.

**Comment by jenyyy4** [comment]
@Propo41 I would like to work on this issue, please assign it to me.

**Comment by Propo41** [comment]
This has probably something to do with the mock api service. The actual one (`google-api.service.ts`) works as expected.
